"""initial

Revision ID: fc73d9744563
Revises: 
Create Date: 2022-12-17 14:58:09.838809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc73d9744563'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Workshop',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('maxTeilnehmer', mysql.INTEGER(display_width=10), nullable=True),
    sa.Column('teilnehmer', mysql.INTEGER(display_width=10), nullable=True),
    sa.Column('klasse', sa.Text(), nullable=True),
    sa.Column('kurzbeschreibung', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('Person',
    sa.Column('id', mysql.INTEGER(display_width=10), nullable=False),
    sa.Column('vorname', sa.Text(), nullable=True),
    sa.Column('nachname', sa.Text(), nullable=True),
    sa.Column('klasse', mysql.INTEGER(display_width=10), nullable=True),
    sa.Column('erstwunsch', sa.String(length=255), nullable=True),
    sa.Column('zweitwunsch', sa.String(length=255), nullable=True),
    sa.Column('drittwunsch', sa.String(length=255), nullable=True),
    sa.Column('projekt', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['drittwunsch'], ['Workshop.name'], ),
    sa.ForeignKeyConstraint(['erstwunsch'], ['Workshop.name'], ),
    sa.ForeignKeyConstraint(['projekt'], ['Workshop.name'], ),
    sa.ForeignKeyConstraint(['zweitwunsch'], ['Workshop.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Person_drittwunsch'), 'Person', ['drittwunsch'], unique=False)
    op.create_index(op.f('ix_Person_erstwunsch'), 'Person', ['erstwunsch'], unique=False)
    op.create_index(op.f('ix_Person_projekt'), 'Person', ['projekt'], unique=False)
    op.create_index(op.f('ix_Person_zweitwunsch'), 'Person', ['zweitwunsch'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Person_zweitwunsch'), table_name='Person')
    op.drop_index(op.f('ix_Person_projekt'), table_name='Person')
    op.drop_index(op.f('ix_Person_erstwunsch'), table_name='Person')
    op.drop_index(op.f('ix_Person_drittwunsch'), table_name='Person')
    op.drop_table('Person')
    op.drop_table('Workshop')
    # ### end Alembic commands ###
