"""finish tippfehler

Revision ID: 1b56a126769b
Revises: a4c55186a1c3
Create Date: 2023-01-07 22:32:16.605244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b56a126769b'
down_revision = 'a4c55186a1c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Job', sa.Column('finish', sa.DateTime(), nullable=True))
    op.drop_column('Job', 'finsh')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Job', sa.Column('finsh', mysql.DATETIME(), nullable=True))
    op.drop_column('Job', 'finish')
    # ### end Alembic commands ###
