"""relation\

Revision ID: 1fa315de92d0
Revises: 268dbd3199ab
Create Date: 2022-12-06 00:01:18.432946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa315de92d0'
down_revision = '268dbd3199ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
