"""relationsh\

Revision ID: 268dbd3199ab
Revises: b0173ab8c51f
Create Date: 2022-12-05 23:59:37.701159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268dbd3199ab'
down_revision = 'b0173ab8c51f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
