"""backref

Revision ID: 4e59f8a6519a
Revises: 54d0c818348c
Create Date: 2022-12-06 13:40:45.397813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e59f8a6519a'
down_revision = '54d0c818348c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
