"""relation\

Revision ID: 54d0c818348c
Revises: 1fa315de92d0
Create Date: 2022-12-06 00:02:37.181649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d0c818348c'
down_revision = '1fa315de92d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
