"""rel

Revision ID: 5fc1644985d8
Revises: 4e59f8a6519a
Create Date: 2022-12-06 13:45:04.501960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc1644985d8'
down_revision = '4e59f8a6519a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
