"""rel1

Revision ID: 660b48c54555
Revises: 5fc1644985d8
Create Date: 2022-12-06 13:49:43.922358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660b48c54555'
down_revision = '5fc1644985d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
