"""added cost

Revision ID: 947105370583
Revises: 1b56a126769b
Create Date: 2023-02-09 17:01:46.631353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947105370583'
down_revision = '1b56a126769b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Job', sa.Column('cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Job', 'cost')
    # ### end Alembic commands ###
