"""Neues init

Revision ID: a4c55186a1c3
Revises: 
Create Date: 2023-01-07 17:57:11.702504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4c55186a1c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Workshop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('minTeilnehmer', mysql.INTEGER(display_width=10), nullable=True),
    sa.Column('maxTeilnehmer', mysql.INTEGER(display_width=10), nullable=True),
    sa.Column('minKlasse', mysql.INTEGER(display_width=10), nullable=True),
    sa.Column('maxKlasse', mysql.INTEGER(display_width=10), nullable=True),
    sa.Column('anzahlTeilnehmer', mysql.INTEGER(display_width=10), nullable=True),
    sa.Column('kurzbeschreibung', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Person',
    sa.Column('id', mysql.INTEGER(display_width=10), nullable=False),
    sa.Column('vorname', sa.Text(), nullable=True),
    sa.Column('nachname', sa.Text(), nullable=True),
    sa.Column('klassenstufe', mysql.INTEGER(display_width=10), nullable=True),
    sa.Column('_wunsch1_id', sa.Integer(), nullable=True),
    sa.Column('_wunsch2_id', sa.Integer(), nullable=True),
    sa.Column('_wunsch3_id', sa.Integer(), nullable=True),
    sa.Column('_projekt_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['_projekt_id'], ['Workshop.id'], ),
    sa.ForeignKeyConstraint(['_wunsch1_id'], ['Workshop.id'], ),
    sa.ForeignKeyConstraint(['_wunsch2_id'], ['Workshop.id'], ),
    sa.ForeignKeyConstraint(['_wunsch3_id'], ['Workshop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_Person__projekt_id'), 'Person', ['_projekt_id'], unique=False)
    op.create_index(op.f('ix_Person__wunsch1_id'), 'Person', ['_wunsch1_id'], unique=False)
    op.create_index(op.f('ix_Person__wunsch2_id'), 'Person', ['_wunsch2_id'], unique=False)
    op.create_index(op.f('ix_Person__wunsch3_id'), 'Person', ['_wunsch3_id'], unique=False)
    op.create_table('Job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('finsh', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_by', mysql.INTEGER(display_width=10), nullable=True),
    sa.ForeignKeyConstraint(['started_by'], ['Person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Job_started_by'), 'Job', ['started_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Job_started_by'), table_name='Job')
    op.drop_table('Job')
    op.drop_index(op.f('ix_Person__wunsch3_id'), table_name='Person')
    op.drop_index(op.f('ix_Person__wunsch2_id'), table_name='Person')
    op.drop_index(op.f('ix_Person__wunsch1_id'), table_name='Person')
    op.drop_index(op.f('ix_Person__projekt_id'), table_name='Person')
    op.drop_table('Person')
    op.drop_table('Workshop')
    # ### end Alembic commands ###
