"""relationshi\

Revision ID: b0173ab8c51f
Revises: 5308f978180d
Create Date: 2022-12-05 23:58:16.713647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0173ab8c51f'
down_revision = '5308f978180d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Schueler', sa.Column('erstwunsch', sa.String(length=255), nullable=True))
    op.add_column('Schueler', sa.Column('zweitwunsch', sa.String(length=255), nullable=True))
    op.add_column('Schueler', sa.Column('drittwunsch', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_Schueler_drittwunsch'), 'Schueler', ['drittwunsch'], unique=False)
    op.create_index(op.f('ix_Schueler_erstwunsch'), 'Schueler', ['erstwunsch'], unique=False)
    op.create_index(op.f('ix_Schueler_zweitwunsch'), 'Schueler', ['zweitwunsch'], unique=False)
    op.create_foreign_key(None, 'Schueler', 'Workshop', ['zweitwunsch'], ['name'])
    op.create_foreign_key(None, 'Schueler', 'Workshop', ['erstwunsch'], ['name'])
    op.create_foreign_key(None, 'Schueler', 'Workshop', ['drittwunsch'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Schueler', type_='foreignkey')
    op.drop_constraint(None, 'Schueler', type_='foreignkey')
    op.drop_constraint(None, 'Schueler', type_='foreignkey')
    op.drop_index(op.f('ix_Schueler_zweitwunsch'), table_name='Schueler')
    op.drop_index(op.f('ix_Schueler_erstwunsch'), table_name='Schueler')
    op.drop_index(op.f('ix_Schueler_drittwunsch'), table_name='Schueler')
    op.drop_column('Schueler', 'drittwunsch')
    op.drop_column('Schueler', 'zweitwunsch')
    op.drop_column('Schueler', 'erstwunsch')
    # ### end Alembic commands ###
