"""Schueler/Lehrer

Revision ID: ba19337b6c4f
Revises: 660b48c54555
Create Date: 2022-12-09 18:47:01.150120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba19337b6c4f'
down_revision = '660b48c54555'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Schueler', sa.Column('position', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Schueler', 'position')
    # ### end Alembic commands ###
