"""idWorkshop

Revision ID: c00e87f2c16e
Revises: c1f1ebaac55c
Create Date: 2023-01-07 00:55:25.243932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c00e87f2c16e'
down_revision = 'c1f1ebaac55c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workshop', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('Workshop', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Workshop', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('Workshop', 'id')
    # ### end Alembic commands ###
