"""self.position

Revision ID: c025604bbee2
Revises: e0f135872a8f
Create Date: 2022-12-12 19:10:45.046551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c025604bbee2'
down_revision = 'e0f135872a8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Schueler', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Schueler', sa.Column('position', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
