"""StrukturUpdate

Revision ID: c1f1ebaac55c
Revises: fc73d9744563
Create Date: 2023-01-06 23:34:38.338510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1f1ebaac55c'
down_revision = 'fc73d9744563'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Person', sa.Column('klassenstufe', mysql.INTEGER(display_width=10), nullable=True))
    op.drop_column('Person', 'klasse')
    op.add_column('Workshop', sa.Column('minTeilnehmer', mysql.INTEGER(display_width=10), nullable=True))
    op.add_column('Workshop', sa.Column('minKlasse', mysql.INTEGER(display_width=10), nullable=True))
    op.add_column('Workshop', sa.Column('maxKlasse', mysql.INTEGER(display_width=10), nullable=True))
    op.add_column('Workshop', sa.Column('anzahlTeilnehmer', mysql.INTEGER(display_width=10), nullable=True))
    op.drop_column('Workshop', 'teilnehmer')
    op.drop_column('Workshop', 'klasse')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workshop', sa.Column('klasse', mysql.TEXT(), nullable=True))
    op.add_column('Workshop', sa.Column('teilnehmer', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True))
    op.drop_column('Workshop', 'anzahlTeilnehmer')
    op.drop_column('Workshop', 'maxKlasse')
    op.drop_column('Workshop', 'minKlasse')
    op.drop_column('Workshop', 'minTeilnehmer')
    op.add_column('Person', sa.Column('klasse', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True))
    op.drop_column('Person', 'klassenstufe')
    # ### end Alembic commands ###
