"""self-korrektur

Revision ID: e8fd19754c4c
Revises: c025604bbee2
Create Date: 2022-12-12 19:20:52.569388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8fd19754c4c'
down_revision = 'c025604bbee2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('Person',
    # sa.Column('id', mysql.INTEGER(display_width=10), nullable=False),
    # sa.Column('vorname', sa.Text(), nullable=True),
    # sa.Column('nachname', sa.Text(), nullable=True),
    # sa.Column('klasse', mysql.INTEGER(display_width=10), nullable=True),
    # sa.Column('erstwunsch', sa.String(length=255), nullable=True),
    # sa.Column('zweitwunsch', sa.String(length=255), nullable=True),
    # sa.Column('drittwunsch', sa.String(length=255), nullable=True),
    # sa.Column('projekt', sa.String(length=255), nullable=True),
    # sa.Column('position', sa.Text(), nullable=True),
    # sa.Column('username', sa.Text(), nullable=True),
    # sa.Column('password', sa.Text(), nullable=True),
    # sa.ForeignKeyConstraint(['drittwunsch'], ['Workshop.name'], ),
    # sa.ForeignKeyConstraint(['erstwunsch'], ['Workshop.name'], ),
    # sa.ForeignKeyConstraint(['projekt'], ['Workshop.name'], ),
    # sa.ForeignKeyConstraint(['zweitwunsch'], ['Workshop.name'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_Person_drittwunsch'), 'Person', ['drittwunsch'], unique=False)
    # op.create_index(op.f('ix_Person_erstwunsch'), 'Person', ['erstwunsch'], unique=False)
    # op.create_index(op.f('ix_Person_projekt'), 'Person', ['projekt'], unique=False)
    # op.create_index(op.f('ix_Person_zweitwunsch'), 'Person', ['zweitwunsch'], unique=False)
    # op.drop_index('ix_Schueler_drittwunsch', table_name='Schueler')
    # op.drop_index('ix_Schueler_erstwunsch', table_name='Schueler')
    # op.drop_index('ix_Schueler_projekt', table_name='Schueler')
    # op.drop_index('ix_Schueler_zweitwunsch', table_name='Schueler')
    # op.drop_table('Schueler')
    op.drop_table('Schueler')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Schueler',
    sa.Column('id', mysql.INTEGER(display_width=10), autoincrement=True, nullable=False),
    sa.Column('vorname', mysql.TEXT(), nullable=True),
    sa.Column('nachname', mysql.TEXT(), nullable=True),
    sa.Column('klasse', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True),
    sa.Column('projekt', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('erstwunsch', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('zweitwunsch', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('drittwunsch', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('username', mysql.TEXT(), nullable=True),
    sa.Column('password', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['drittwunsch'], ['Workshop.name'], name='Schueler_ibfk_7'),
    sa.ForeignKeyConstraint(['erstwunsch'], ['Workshop.name'], name='Schueler_ibfk_6'),
    sa.ForeignKeyConstraint(['projekt'], ['Workshop.name'], name='Schueler_ibfk_4'),
    sa.ForeignKeyConstraint(['zweitwunsch'], ['Workshop.name'], name='Schueler_ibfk_5'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Schueler_zweitwunsch', 'Schueler', ['zweitwunsch'], unique=False)
    op.create_index('ix_Schueler_projekt', 'Schueler', ['projekt'], unique=False)
    op.create_index('ix_Schueler_erstwunsch', 'Schueler', ['erstwunsch'], unique=False)
    op.create_index('ix_Schueler_drittwunsch', 'Schueler', ['drittwunsch'], unique=False)
    op.drop_index(op.f('ix_Person_zweitwunsch'), table_name='Person')
    op.drop_index(op.f('ix_Person_projekt'), table_name='Person')
    op.drop_index(op.f('ix_Person_erstwunsch'), table_name='Person')
    op.drop_index(op.f('ix_Person_drittwunsch'), table_name='Person')
    op.drop_table('Person')
    # ### end Alembic commands ###
